### PR TITLE
Fix USB PID for Logitech C920

### PR DESCRIPTION
**Pull request by raccube**

### CODE REVIEW

**Comment by trickeydan** [comment]
What was the old PID for? How do we know that this one is correct?

**Comment by raccube** [comment]
We know this one is correct because I've had to keep patching it locally while testing. ~~The old one was there due to confusion.~~

**Comment by raccube** [comment]
Actually, ignore the second half of what I just said, both are correct. The one I have is a C920 Pro. I doubt they use a different lens so the calibration should still be correct. I'll update this PR later. 
image

**Comment by trickeydan** [comment]
Do we want 08E5 too then?

**Review by trickeydan — APPROVED** [review]

**Pull request merged**
